import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "@/components/providers/toast-provider";



export const metadata: Metadata = {
  title: "Smart Classroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={`antialiased`}>
        <ToastProvider/>
        {children}
      </body>
    </html>
  );
}
