import type { Metadata } from "next";
import "./globals.css";
import ToastProvider from "@/components/providers/toast-provider";
import ConfettiProvider from "@/components/providers/confetti-provider";
import Script from "next/script";



export const metadata: Metadata = {
  title: "Smart Classroom",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      </head>
        {/* Google Tag Manager Script */}
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=G-M0Z4QHZ2ED"
          async
        />
        <Script
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-M0Z4QHZ2ED');
            `,
          }}
        />
      <body  className={`antialiased`}>
        <ConfettiProvider/>
        <ToastProvider/>
        {children}
      </body>
    </html>
  );
}
